### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [HeidiBash/ColmarAcademy#1]
Summary Grade: Satisfactory

Good job with your code! I really liked the way you clearly organized your code with whitespace, indentation, and comments. It makes your code really easy to navigate and read, as well as visually pleasing. Also, I really like the way you used classes and ids to group your sections together. As your code grows in size, this will help organize and manage your website. You also gave tremendous effort into your mobile resizing. Great start to the Ready program! 

I included a few notes in both the html file for you to think more critically about. You can find these comments in the issues tab of your github. First, you did a good job with your mobile resizing. You website looks good in many sizes but when the screen becomes narrow enough, you still need to scroll horizontal to see and read everything. In the future, you can consider helpers and libraries like Bootstrap (http://getbootstrap.com/) to help you build a responsive website. This library does a lot of pre-arranging and adjusting so that you don't have to write such detailed css. Also, don't forget to add semi-colons to your special characters to complete them. In most text editors, you'll be able to see the red-highlights when there's a problem.

**Comment by HeidiBash** [comment]
Thanks so much for the review.  I appreciate your comments.
